# Random Forrest Regressor

## Import Data and run Regressor

In [2]:
import pandas as pd
model = pd.read_csv('final_model.csv')

In [3]:
#pandas max columns
pd.set_option('display.max_columns', None)
model.head()

,Tract,neighborhood,Labor Force,Unemployed,Employed,Family Poverty,No HS,Some HS,HS Graduates,Bachelors Degree,Grad/Prof Degree,Private Health Ins,Public Health Ins,No Health Ins,No Vehicles,One Vehicle,Two Vehicles,Three+ Vehicles,Drive Alone,Carpooled,Walked,Other means,WFH,Public Transit,Total Population,Male,Female,Census Tract Number,Life Expectancy,Life Expectancy Standard Error,NAME10,Life Expectancy_abvavg,Life_Expectancy_Difference,Unemployed_cat_10-15%,Unemployed_cat_15-20%,Unemployed_cat_20-25%,Unemployed_cat_25 or more,Unemployed_cat_5-10%,Unemployed_cat_less than 5%,sex_cat_More Men,sex_cat_More Women,vehicle_cat_No Vehicles,vehicle_cat_One Vehicle,vehicle_cat_Three+ Vehicles,vehicle_cat_Two Vehicles,transport_cat_Carpooled,transport_cat_Drive Alone,transport_cat_Public Transit,transport_cat_Walked,education_cat_Bachelors Degree,education_cat_Grad/Prof Degree,education_cat_HS Graduates,education_cat_No HS,education_cat_Some HS,health_ins_cat_No Health Ins,health_ins_cat_Private Health Ins,health_ins_cat_Public Health Ins,area_Central,area_Far North Side,area_Far South Side,area_Far Southwest Side,area_North Side,area_Northwest Side,area_South Side,area_Southwest Side,area_West Side
0,271400.0,EAST GARFIELD PARK,456.0,8.5,39.9,43.3,3.0,22.9,26.0,11.0,3.0,30.1,58.8,13.8,30.2,54.2,15.1,0.5,31.0,8.3,0.5,7.8,11.2,41.2,1185.0,51.9,48.1,2714.0,68.600000,3.622800,2714.0,0,-8.163070,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1
1,280100.0,NEAR WEST SIDE,5892.0,2.7,88.6,0.0,0.0,0.0,3.8,49.4,39.9,94.5,4.7,3.6,31.0,58.1,9.5,1.3,25.4,3.5,43.6,6.1,7.3,14.1,6811.0,49.3,50.7,2801.0,74.068631,2.721147,2801.0,0,-2.694439,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2,310300.0,LOWER WEST SIDE,1126.0,11.1,66.0,14.2,14.4,7.9,15.6,26.3,11.7,49.5,23.8,31.4,21.7,37.6,30.5,10.2,51.7,5.7,5.5,10.8,3.6,22.6,1673.0,59.0,41.0,3103.0,79.100000,3.222500,3103.0,1,2.336930,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3,200200.0,HERMOSA,2440.0,7.4,57.7,26.9,22.8,14.5,34.6,6.8,2.6,32.8,49.0,21.9,24.7,32.6,30.3,12.3,66.0,8.9,4.1,1.6,2.0,17.4,4815.0,50.8,49.2,2002.0,78.500000,1.940100,2002.0,1,1.736930,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0
4,221400.0,LOGAN SQUARE,2048.0,2.9,76.9,12.7,4.5,8.8,22.6,29.6,14.7,63.7,14.8,24.2,22.0,60.7,15.3,2.0,38.8,5.7,0.3,4.4,9.6,41.2,3034.0,58.3,41.7,2214.0,80.900000,3.074800,2214.0,1,4.136930,0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0

In [4]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Assuming there's a feature in the dataset that can serve as a proxy for life expectancy or health outcomes.
# For demonstration, we'll choose 'Employed' percentage as a proxy, assuming higher employment rates correlate with better health outcomes.
# This is a simplification and may not hold true in all contexts.
data=model

target_variable = 'Life_Expectancy_Difference'  # This is our assumed proxy for life expectancy or health outcomes.

# Dropping non-numerical and non-relevant columns for feature selection
features = data.drop(columns=['Tract', 'neighborhood', 'Life_Expectancy_Difference', 'Life Expectancy_abvavg','Life Expectancy',target_variable])

# Splitting the data into features (X) and target (y)
X = features
y = data[target_variable]

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardizing the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Using Random Forest for feature importance
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train_scaled, y_train)

# Extracting feature importance
feature_importances = rf.feature_importances_

# Mapping feature names to their importance scores
importance_dict = dict(zip(features.columns, feature_importances))

# Sorting features by importance
sorted_importance = sorted(importance_dict.items(), key=lambda x: x[1], reverse=True)

df_sorted_importance=pd.DataFrame(sorted_importance, columns=['Feature', 'Importance'])
#pandas max rows
pd.set_option('display.max_rows', None)

In [5]:
#rf accuracy
rf_accuracy = rf.score(X_test_scaled, y_test)
print('Random Forest R^2:', rf_accuracy)

Random Forest R^2: 0.6051499855395563

## Feature importance: Life Expectancy Difference

In [7]:
df_sorted_importance

                              Feature  Importance
0                            Employed    0.497955
1                   Public Health Ins    0.056846
2      Life Expectancy Standard Error    0.045548
3                          Unemployed    0.040881
4                    Bachelors Degree    0.032809
5                  Private Health Ins    0.030054
6                      Family Poverty    0.028201
7                               No HS    0.026728
8                             Some HS    0.020596
9                              NAME10    0.015617
10                     Public Transit    0.015596
11                Census Tract Number    0.013983
12                   Grad/Prof Degree    0.012738
13                          Carpooled    0.012664
14                        No Vehicles    0.011588
15                       Two Vehicles    0.011301
16                       HS Graduates    0.011038
17                    Three+ Vehicles    0.010940
18                        Labor Force    0.010652
19                      No Health Ins    0.010536
20                        One Vehicle    0.010472
21                             Walked    0.010242
22                                WFH    0.009764
23                   Total Population    0.009129
24                        Other means    0.008774
25                        Drive Alone    0.008407
26                             Female    0.007012
27                               Male    0.006493
28                area_Far South Side    0.001290
29                area_Southwest Side    0.001125
30                    area_South Side    0.000991
31                       area_Central    0.000909
32                area_Far North Side    0.000740
33     education_cat_Bachelors Degree    0.000668
34            area_Far Southwest Side    0.000640
35                     area_West Side    0.000640
36       transport_cat_Public Transit    0.000553
37               Unemployed_cat_5-10%    0.000531
38              Unemployed_cat_10-15%    0.000516
39            vehicle_cat_One Vehicle    0.000413
40          Unemployed_cat_25 or more    0.000408
41         education_cat_HS Graduates    0.000401
42     education_cat_Grad/Prof Degree    0.000398
43                 sex_cat_More Women    0.000375
44          transport_cat_Drive Alone    0.000366
45                   sex_cat_More Men    0.000327
46   health_ins_cat_Public Health Ins    0.000313
47                    area_North Side    0.000292
48           vehicle_cat_Two Vehicles    0.000283
49            vehicle_cat_No Vehicles    0.000271
50              Unemployed_cat_15-20%    0.000235
51                area_Northwest Side    0.000173
52  health_ins_cat_Private Health Ins    0.000154
53              Unemployed_cat_20-25%    0.000142
54        Unemployed_cat_less than 5%    0.000129
55                education_cat_No HS    0.000098
56              education_cat_Some HS    0.000030
57               transport_cat_Walked    0.000017
58            transport_cat_Carpooled    0.000002
59       health_ins_cat_No Health Ins    0.000002
60        vehicle_cat_Three+ Vehicles    0.000000