Logistic Regression

In [4]:
import pandas as pd
df = pd.read_csv('final_model.csv')

In [5]:
pd.set_option('display.max_columns', None)
df.head()

,Tract,neighborhood,Labor Force,Unemployed,Employed,Family Poverty,No HS,Some HS,HS Graduates,Bachelors Degree,Grad/Prof Degree,Private Health Ins,Public Health Ins,No Health Ins,No Vehicles,One Vehicle,Two Vehicles,Three+ Vehicles,Drive Alone,Carpooled,Walked,Other means,WFH,Public Transit,Total Population,Male,Female,Census Tract Number,Life Expectancy,Life Expectancy Standard Error,NAME10,Life Expectancy_abvavg,Life_Expectancy_Difference,Unemployed_cat_10-15%,Unemployed_cat_15-20%,Unemployed_cat_20-25%,Unemployed_cat_25 or more,Unemployed_cat_5-10%,Unemployed_cat_less than 5%,sex_cat_More Men,sex_cat_More Women,vehicle_cat_No Vehicles,vehicle_cat_One Vehicle,vehicle_cat_Three+ Vehicles,vehicle_cat_Two Vehicles,transport_cat_Carpooled,transport_cat_Drive Alone,transport_cat_Public Transit,transport_cat_Walked,education_cat_Bachelors Degree,education_cat_Grad/Prof Degree,education_cat_HS Graduates,education_cat_No HS,education_cat_Some HS,health_ins_cat_No Health Ins,health_ins_cat_Private Health Ins,health_ins_cat_Public Health Ins,area_Central,area_Far North Side,area_Far South Side,area_Far Southwest Side,area_North Side,area_Northwest Side,area_South Side,area_Southwest Side,area_West Side
0,271400.0,EAST GARFIELD PARK,456.0,8.5,39.9,43.3,3.0,22.9,26.0,11.0,3.0,30.1,58.8,13.8,30.2,54.2,15.1,0.5,31.0,8.3,0.5,7.8,11.2,41.2,1185.0,51.9,48.1,2714.0,68.600000,3.622800,2714.0,0,-8.163070,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1
1,280100.0,NEAR WEST SIDE,5892.0,2.7,88.6,0.0,0.0,0.0,3.8,49.4,39.9,94.5,4.7,3.6,31.0,58.1,9.5,1.3,25.4,3.5,43.6,6.1,7.3,14.1,6811.0,49.3,50.7,2801.0,74.068631,2.721147,2801.0,0,-2.694439,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2,310300.0,LOWER WEST SIDE,1126.0,11.1,66.0,14.2,14.4,7.9,15.6,26.3,11.7,49.5,23.8,31.4,21.7,37.6,30.5,10.2,51.7,5.7,5.5,10.8,3.6,22.6,1673.0,59.0,41.0,3103.0,79.100000,3.222500,3103.0,1,2.336930,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3,200200.0,HERMOSA,2440.0,7.4,57.7,26.9,22.8,14.5,34.6,6.8,2.6,32.8,49.0,21.9,24.7,32.6,30.3,12.3,66.0,8.9,4.1,1.6,2.0,17.4,4815.0,50.8,49.2,2002.0,78.500000,1.940100,2002.0,1,1.736930,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0
4,221400.0,LOGAN SQUARE,2048.0,2.9,76.9,12.7,4.5,8.8,22.6,29.6,14.7,63.7,14.8,24.2,22.0,60.7,15.3,2.0,38.8,5.7,0.3,4.4,9.6,41.2,3034.0,58.3,41.7,2214.0,80.900000,3.074800,2214.0,1,4.136930,0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0

In [14]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

X = df.drop(columns=['Life Expectancy_abvavg', 'Tract', 'neighborhood', 'Census Tract Number', 'NAME10'])

# Adding a constant column for the intercept
X_const = sm.add_constant(X)

# Calculate VIF for each feature
vif_data = pd.DataFrame()
vif_data["feature"] = X_const.columns
vif_data["VIF"] = [variance_inflation_factor(X_const.values, i) for i in range(len(X_const.columns))]

vif_data

/Users/peichin/anaconda3/lib/python3.11/site-packages/statsmodels/regression/linear_model.py:1781: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/Users/peichin/anaconda3/lib/python3.11/site-packages/statsmodels/stats/outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                feature        VIF
0                 const   0.000000
1           Labor Force  25.000832
2            Unemployed  14.056048
3              Employed  10.049905
4        Family Poverty   6.574015
..                  ...        ...
57      area_North Side        inf
58  area_Northwest Side        inf
59      area_South Side        inf
60  area_Southwest Side        inf
61       area_West Side        inf

[62 rows x 2 columns]

In [16]:
pd.set_option('display.max_columns', None)
vif_data.head(60)

                              feature           VIF
0                               const  0.000000e+00
1                         Labor Force  2.500083e+01
2                          Unemployed  1.405605e+01
3                            Employed  1.004990e+01
4                      Family Poverty  6.574015e+00
5                               No HS  7.144265e+00
6                             Some HS  5.100159e+00
7                        HS Graduates  9.483200e+00
8                    Bachelors Degree  1.688952e+01
9                    Grad/Prof Degree  1.296543e+01
10                 Private Health Ins  8.578452e+01
11                  Public Health Ins  4.335489e+01
12                      No Health Ins  1.557991e+01
13                        No Vehicles  7.157077e+04
14                        One Vehicle  2.518447e+04
15                       Two Vehicles  3.907049e+04
16                    Three+ Vehicles  1.093975e+04
17                        Drive Alone  5.157133e+04
18                          Carpooled  7.747670e+03
19                             Walked  1.457729e+04
20                        Other means  2.165857e+03
21                                WFH  2.307352e+03
22                     Public Transit  3.645067e+04
23                   Total Population  2.114854e+01
24                               Male           inf
25                             Female           inf
26                    Life Expectancy           inf
27     Life Expectancy Standard Error  1.459268e+00
28         Life_Expectancy_Difference           inf
29              Unemployed_cat_10-15%           inf
30              Unemployed_cat_15-20%           inf
31              Unemployed_cat_20-25%           inf
32          Unemployed_cat_25 or more           inf
33               Unemployed_cat_5-10%           inf
34        Unemployed_cat_less than 5%           inf
35                   sex_cat_More Men           inf
36                 sex_cat_More Women           inf
37            vehicle_cat_No Vehicles           inf
38            vehicle_cat_One Vehicle           inf
39        vehicle_cat_Three+ Vehicles           inf
40           vehicle_cat_Two Vehicles           inf
41            transport_cat_Carpooled           inf
42          transport_cat_Drive Alone           inf
43       transport_cat_Public Transit           inf
44               transport_cat_Walked           inf
45     education_cat_Bachelors Degree           inf
46     education_cat_Grad/Prof Degree           inf
47         education_cat_HS Graduates           inf
48                education_cat_No HS           inf
49              education_cat_Some HS           inf
50       health_ins_cat_No Health Ins           inf
51  health_ins_cat_Private Health Ins           inf
52   health_ins_cat_Public Health Ins           inf
53                       area_Central           inf
54                area_Far North Side           inf
55                area_Far South Side           inf
56            area_Far Southwest Side           inf
57                    area_North Side           inf
58                area_Northwest Side           inf
59                    area_South Side           inf

In [21]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# List the variables to include based on VIF results
variables_to_include = [
    'Some HS',  # VIF < 5
    'Family Poverty',  # VIF just above 5, but you might choose to include it
    'Drive Alone',
    'Private Health Ins'
]

df['Life Expectancy_abvavg'] = pd.to_numeric(df['Life Expectancy_abvavg'], errors='coerce')
df.dropna(subset=['Life Expectancy_abvavg'], inplace=True)  
y = df['Life Expectancy_abvavg'].astype(int)  

# Select the features based on the variables to include
X = df[variables_to_include]

# Add a constant to the model (intercept term)
X = sm.add_constant(X)

# Fit the logistic regression model
model = sm.Logit(y, X).fit()

# Print the model summary, which includes the log-likelihood
print(model.summary())

Optimization terminated successfully.
         Current function value: 0.480694
         Iterations 6
                             Logit Regression Results
==================================================================================
Dep. Variable:     Life Expectancy_abvavg   No. Observations:                  797
Model:                              Logit   Df Residuals:                      792
Method:                               MLE   Df Model:                            4
Date:                    Thu, 29 Feb 2024   Pseudo R-squ.:                  0.2977
Time:                            22:55:43   Log-Likelihood:                -383.11
converged:                           True   LL-Null:                       -545.50
Covariance Type:                nonrobust   LLR p-value:                 4.882e-69
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  2.7734      0.918      3.021      0.003       0.974       4.573
Some HS               -0.1140      0.026     -4.332      0.000      -0.166      -0.062
Family Poverty        -0.0708      0.013     -5.577      0.000      -0.096      -0.046
Drive Alone           -0.0017      0.007     -0.239      0.811      -0.015       0.012
Private Health Ins     0.0018      0.009      0.196      0.844      -0.016       0.020
======================================================================================

In [22]:
log_likelihood = model.llf

print(f'Log-Likelihood: {log_likelihood}')

Log-Likelihood: -383.1127320232233